[package]
name = "memepoke-reloaded"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
yew-router = "0.15"
serde_json = "1.0"
serde = "1.0.127"
anyhow = "1.0.21"